### ISSUE TITLE
Advance or delay the video

### ISSUE THREAD

**Issue by Smallkan** [asapach/peerflix-server#83] opened 2016-09-02 01:00 UTC
Peerflix is operating normally on my server and Herokuapp!

I used the command: _?ffmpeg=probe_ to view the information and _?ffmpeg=remux_ to view .mkv files?

But I can not advance or delay the video or transmit it in VLC, sometimes it crashes, making the video back to the beginning.

Do you have any solution for this? something that I can install to fix?

I thank you.

**Comment by asapach** [comment] 2016-09-02 09:36
Duplicate of #59. Unfortunately it's a limitation of transcoding (explained [here](https://github.com/asapach/peerflix-server/issues/20#issuecomment-82252626)).
I would suggest that you don't use transcoding with VLC, since it supports all the media formats natively.

**Comment by Smallkan** [comment] 2016-09-02 10:23
Thanks!

**Closed** 2016-11-19 22:07 UTC
Labels: question
